import type { Metadata } from "next";
import dynamic from "next/dynamic";

const DashboardLayout = dynamic(() => import("seeksolution/layouts/DashboardLayout"), { ssr: false })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardLayout>
      {children}
    </DashboardLayout>
  );
}
